### PR TITLE
remove item quantity, barcode / description

### PR DESCRIPTION
**Pull request by jackgoldsmith4**

### CODE REVIEW

**Comment by jackgoldsmith4** [comment]
@Dafondo now users can only reserve one of a certain item at a time. Let me know if I am missing anything here

**Comment by Dafondo** [comment]
Should we also check to make sure that the user doesn't already have an existing (pending or completed) preorder of an item?

For example, I can currently checkout with an item in my cart. Then I can add the same item to my cart and checkout again.

**Comment by jackgoldsmith4** [comment]
@Dafondo yeah, and this is where we need to update the status for preorders (which I've started to just call "orders"). If the item is pending or completed (which I think should change to "reserved" or "in use"), the user shouldn't be allowed to check out another item that's the same. Then, when the item is returned to the closet, the status should change to "completed" and it should be OK again for the user to check out that item. Do you agree with that thinking? If so, I'll add that logic to this PR and resubmit

**Comment by Dafondo** [comment]
@jackgoldsmith4 Yeah, that makes sense to me

**Pull request merged**
